### PR TITLE
Rename expenses.md to README.md

### PR DESCRIPTION
**Pull request by ContentBrewmaster**
Changing file name to README

----
:books: Documentation preview :books:: https://civicactions-handbook--1171.org.readthedocs.build/en/1171/

### CODE REVIEW

**Comment by grugnog** [comment]
@ContentBrewmaster it's not clear to me that expenses makes sense as the top level page for this section. It seems like we would want something more general here?

**Comment by ContentBrewmaster** [comment]
@grugnog typically I would agree but there is a complete overhaul of benefits and policies in the works with Marc, Elizabeth, and Kimberlin. I'm hoping to remove the dependency of that work (which could take a month) on this change so we can install the new editing tool.

**Comment by ContentBrewmaster** [comment]
I don't understand how to fix the redirects file. @dmundra can you help?

**Comment by dmundra** [comment]
> I don't understand how to fix the redirects file. @dmundra can you help?

Yes, it is fixed. The redirects are being added to the end of the file and other pull requests are adding to that same file in the same location which is causing the conflict. So we have to move changes in the PR to come after those new changes.

**Pull request closed without merging**
