### PR TITLE
Mural & tiny side quests

### PR DESCRIPTION
**Pull request by TheBoatyMcBoatFace**
Primarily added Mural documentation, but also updated the main README and added some stuff to `.gitignore`

Signed-off-by: TheBoatyMcBoatFace <bentley.hensel@civicactions.com>

----
📚 Documentation preview 📚: https://civicactions-handbook--1389.org.readthedocs.build/en/1389/

### CODE REVIEW

**Review by dmundra — CHANGES_REQUESTED** [review]
@TheBoatyMcBoatFace can you rebase your branch and update the PR?

**Comment by TheBoatyMcBoatFace** [comment]
@dmundra it has been a _while_ since I updated things from the main repo.

**Comment by dmundra** [comment]
> @dmundra it has been a _while_ since I updated things from the main repo.

Ya and I am still seeing a lot of conflicts. It might be easier to start fresh from the master branch or try rebasing again.

**Comment by TheBoatyMcBoatFace** [comment]
Yea. Good idea @dmundra

**Pull request closed without merging**
