### PR TITLE
Added underline text-decoration for links in content.

### LINKED ISSUE #1088: Added underline text decoration for links in the content
Request from @mgifford

### PR DESCRIPTION
**Pull request by dmundra**
Fixes #1088 

----
:books: Documentation preview :books:: https://civicactions-handbook--1093.org.readthedocs.build/en/1093/

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford can you take a look in the preview site https://civicactions-handbook--1093.org.readthedocs.build/en/1093/ and see if the changes to the link decoration work better?

**Comment by mgifford** [comment]
That's much better @dmundra would like to see it go one step further and also hit the main navigation, but this is a good start. Maybe that should go in a different PR.

**Comment by dmundra** [comment]
> That's much better @dmundra would like to see it go one step further and also hit the main navigation, but this is a good start. Maybe that should go in a different PR.

I can do it in the same PR. The question though would underlines in the main navigation be unnecessary since it does stand out as navigation? You can see the UK example doesn't have it.

**Review by ContentBrewmaster — APPROVED** [review]
Not sure about applying the underline to navigation. @mgifford is there an accessibility issue with navigation that not's underlined?

**Comment by mgifford** [comment]
Screenshot from handbook header

If it is unclear if it is a link or other text, then I'd say they should be. Now the navigation could be in something that is more clearly identified as an area of focus. I don't think it is a problem on mobile views.   
  
I'd like to have the text bigger in the navigation here too. I find it a bit hard to read.

**Comment by dmundra** [comment]
@mgifford good points. Could we rope in a front-ender or designer to chime in and suggest the CSS changes for that? I feel that the menu changes should be reviewed that does work with the overall theme and different screen sizes. I am not the best judge of those changes.

**Comment by adriancooke** [comment]
@dmundra @ContentBrewmaster @mgifford tagging @qjac for an FE perspective. I don’t think we necessarily need underlines, but I think it would help to improve the contrast and possibly size on the main nav text, and possibly use an underline (and maybe even boldface) to differentiate the selected item.

Minimally…
- opacity: increase to at least 0.8
- font-size: increase to at least 0.8 rem

_Current_
ca-guidebook-1093-menu-current

_opacity: 0.8;_
ca-guidebook-1093-menu-opacity

_opacity: 0.8; font-size: 0.8 rem; Active state bold and underlined_
ca-guidebook-1093-menu-size-active-bold-underline

_opacity: 1; font-size: 0.8 rem; Active state bold and underlined_
ca-guidebook-1093-menu-size-opacity-active-bold-underline

**Comment by dmundra** [comment]
Thanks @adriancooke. I like your suggestions.

**Comment by dmundra** [comment]
@adriancooke I pushed a version of your suggestions and you can see it on https://civicactions-handbook--1093.org.readthedocs.build/en/1093/ (might have to cache-clear refresh to see the changes). How does that look and also what would you like to see on hover of the menu item? I went with underline is shown on hover. Adding bold on hover had too much motion I think.

@qjac please review my code as well when you get a chance.

**Comment by adriancooke** [comment]
@dmundra I like that version a lot better, and link underline on hover seems like a good choice to me. Also, @ContentBrewmaster while I was reviewing, I also wondered about whether the word “Common” was needed in “Common practices and tools.” I know a lot of research work went into the new labels, so I don’t mean to second-guess. Just a thought to see how it strikes you.

**Review by qjac — APPROVED** [review]
I like the updates! The code looks solid and ready to merge.

**Comment by ContentBrewmaster** [comment]
I like the improved contrast and bigger font too. @dmundra I'd love a shorter label but we needed to differentiate between what is shared or common practice, and the practice area content. @adriancooke curious as to whether you think "Shared practices and tools" has the same meaning? I'm inclined to switch to that phrase which would be slightly less lengthy and introduce a different capital letter in the navigation, which would help readers differentiate the sections.

**Review by ContentBrewmaster — APPROVED** [review]

**Comment by adriancooke** [comment]
@ContentBrewmaster great idea and thanks for pointing out the need to differentiate it from Practice areas. I think “Shared” works well, and I think it conveys the same meaning!

**Pull request merged**
