### PR TITLE
Addition of timekeeping policy

### PR DESCRIPTION
**Pull request by prasuna-m**
Migrating 'Timekeeping Policy and Procedures' from 
https://docs.google.com/document/d/1lpvqgY4Cjo3DBtKrtqykbALXBg1TaitK/edit#

----
📚 Documentation preview 📚: https://civicactions-handbook--1099.org.readthedocs.build/en/1099/

### CODE REVIEW

**Comment by dmundra** [comment]
@prasuna-m thank you for creating this and it is looking good. Here is the preview of the page https://civicactions-handbook--1099.org.readthedocs.build/en/1099/company-policies/timekeeping-policies/

I do have following feedback:

* Can you change the title of this pull request from 'Prasuna m patch 1' to something like 'Addition of timekeeping policy'?
* Review the problems and suggestions in the 'File changes' tab. I think the use of headers could be adjusted. Definitely touch base with @ContentBrewmaster to work on the content. Also see https://squidfunk.github.io/mkdocs-material/reference/admonitions/ as an example to add a block around the policy date.
* When you can also add the new page to `.config/mkdocs.yml` file to add the file to the navigation?

**Comment by prasuna-m** [comment]
@dmundra, Thanks for your comments. I have made the changes you have suggested. Please review when you get a chance. 

Btw, the Admonition block as mentioned in the link didn't work. So, I put the policy date in a table similar to the one that was used in the code-of-conduct.md page.

**Comment by dmundra** [comment]
> @dmundra, Thanks for your comments. I have made the changes you have suggested. Please review when you get a chance.

Thank you @prasuna-m for fixing the header errors so that is looking good to me. I will approve but this will still need legal approval to be mergeable. Also differ to @ContentBrewmaster for content conversation.

> Btw, the Admonition block as mentioned in the link didn't work. So, I put the policy date in a table similar to the one that was used in the code-of-conduct.md page.

Whoops that is my fault, admonition takes additional configuration. We can look at that later if the feature is desired.

**Review by dmundra — APPROVED** [review]
Approving the menu change and no merge blocking errors in the content. Differ to @marctjones and @ContentBrewmaster for content changes.

**Comment by ContentBrewmaster** [comment]
@dmundra I'm meeting with Prasuna and Montana this afternoon to review style considerations.

**Comment by ContentBrewmaster** [comment]
Sent recommended edits to policy and new FAQ content to Marc and Elizabeth this morning for review.

**Review by ContentBrewmaster — APPROVED** [review]

**Comment by ContentBrewmaster** [comment]
This addition dependent on separate branch for new timekeeping guidance #1194

**Review by ContentBrewmaster — APPROVED** [review]
Pending decision to release policy and new timesheet guidance together.

**Review by elizabethraley — APPROVED** [review]

**Pull request merged**
