### PR TITLE
Added editorconfig file with indent configuration.

### PR DESCRIPTION
**Pull request by dmundra**
This is about to update all files and reset indents.

Compare https://guidebook.civicactions.com/en/latest/about-this-guidebook/ to https://civicactions-handbook--1053.org.readthedocs.build/en/1053/about-this-guidebook/ and you see the checklist is intended correctly.

----
:books: Documentation preview :books:: https://civicactions-handbook--1053.org.readthedocs.build/en/1053/

### CODE REVIEW

**Review by grugnog — CHANGES_REQUESTED** [review]
This looks good - however I wonder if we should use [.editorconfig instead of .prettierrc](https://prettier.io/docs/en/configuration.html#editorconfig)?
This would have the advantage of [configuring most local editors](https://editorconfig.org/) to use this indent, and possibly even [the Github editor](https://github.com/editorconfig/editorconfig.github.com/pull/48) (although that is a bit unclear if this works with the MD buttons).

**Comment by dmundra** [comment]
That is a good idea @grugnog. I like that file better to specifying the indentation.

**Review by marctjones — APPROVED** [review]
Approving since this looks like it is just the formatting changes as described

**Review by grugnog — APPROVED** [review]

**Comment by grugnog** [comment]
@dmundra I think the check fails are accounted for (the first is a bug due to the extra-long diff, the second is a broken link we have an open ticket for). If you think we are OK to rebase the outstanding PRs then let me know and I can go ahead and force merge this.

**Comment by dmundra** [comment]
@grugnog ya I am happy to rebase outstanding PRs!

**Pull request merged**
