### PR TITLE
Delete harvest-forecast.md

### PR DESCRIPTION
**Pull request by akaroleff**
[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/akaroleff-patch-4/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Comment by dmundra** [comment]
@akaroleff looks like a couple of pages have a link to the deleted page.

```
WARNING  -  Documentation file '010-welcome-to-civicactions/training/orientation-meetings.md' contains a link to '050-how-we-work/tools/harvest-forecast.md' which is not found in the documentation files.
WARNING  -  Documentation file '070-project-management/pm-training.md' contains a link to '050-how-we-work/tools/harvest-forecast.md' which is not found in the documentation files.
```

I can approve this in any case if you want to move forward with the deletion.

**Comment by grugnog** [comment]
@akaroleff @dmundra we will need to correct the broken links before Github will let us merge (even if it is approved).

**Comment by akaroleff** [comment]
removed reference to PM page /070-project-management/pm-training.md the other page has already been deleted 010-welcome-to-civicactions/training/orientation-meetings.md -

**Comment by grugnog** [comment]
I think there is still 1 broken link to fix/remove before we can delete this:

> Documentation file '070-project-management/pm-training.md' contains a link to '050-how-we-work/tools/harvest-forecast.md' which is not found in the documentation files.

**Review by dmundra — APPROVED** [review]
Looks like the errors are cleared.

**Pull request merged**
