### PR TITLE
simplify phishing reporting

### PR DESCRIPTION
**Pull request by openprivacy**
Removed unnecessarily complicated steps (was 7 steps, now three).

### CODE REVIEW

**Review by grugnog — APPROVED** [review]
Much improved!

**Comment by openprivacy** [comment]
@alanna-casey can you review (and approve ;) this update?

**Comment by grugnog** [comment]
@openprivacy if you could move this to a CivicActions/handbook branch (rather than your fork) that would allow the tests to complete. Currently Gitlab CI doesn't run on Github forks.

**Comment by openprivacy** [comment]
@grugnog (I had thought forks were preferred) I believe I created the branch properly: https://github.com/CivicActions/handbook/pull/669

**Comment by openprivacy** [comment]
Since #669 is created, closing this PR...

**Pull request closed without merging**
