### PR TITLE
Recreating Drupal blogs in handbook and updating links

### LINKED ISSUE #902: Broken link: Backend Development > Drupal-specific Coding Standards
Link "[The Most Important Decision In Developing A Drupal Site: Contributed Vs. Custom Development](https://civicactions.com/blog/developing-drupal-site-contributed-vs-custom-development/)" results in 404. Guessing we took this blog post off our Medium page.

### PR DESCRIPTION
**Pull request by dmundra**
Should we resurrect this post https://web.archive.org/web/20140325033541/http://www.civicactions.com/blog/Drupal_Developer_Tips_Getting_Most_out_Open_Source or point to the archive link (this change) or remove the link reference all together?

Yes for resurrection!

Closes #902 

[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/dmundra-patch-1/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Comment by openprivacy** [comment]
I really like Nedjo's two papers (the other one is linked in the first sentence "recently suggested" also in this page at line 60) and believe they contribute to CivicActions' culture. I'd love to have them somewhere that they can be found more easily.

**Comment by dmundra** [comment]
@openprivacy thanks for pointing that out. I think maybe add it to the handbook? I can do that.

**Comment by grugnog** [comment]
I think adding that post to the handbook (perhaps with some updates) would be great - we should keep some attribution for Nedjo :)

**Comment by dmundra** [comment]
@openprivacy and @grugnog recreated the posts in the handbook. You can see them previewed here: https://handbook.civicactions.com/en/dmundra-patch-1/060-engineering/most-important-decision-in-developing-a-drupal-site-contributed-vs-custom-development/ and https://handbook.civicactions.com/en/dmundra-patch-1/060-engineering/drupal-developer-tips-for-getting-the-most-out-of-open-source/

@grugnog we are running into markdown table issues with the retext-sentence-spacing linter (issue reported here https://github.com/retextjs/retext-sentence-spacing/issues/9). A workaround could be I put in an HTML table. You have a preference or ideas?

**Comment by openprivacy** [comment]
So happy to see these coming back!

**Comment by dmundra** [comment]
> @grugnog we are running into markdown table issues with the retext-sentence-spacing linter (issue reported here [retextjs/retext-sentence-spacing#9](https://github.com/retextjs/retext-sentence-spacing/issues/9)). A workaround could be I put in an HTML table. You have a preference or ideas?

Using HTML table for now. The retext-sentence-spacing author recommended [remark-gfm](https://github.com/remarkjs/remark-gfm) as a solution which maybe we should add it to our linting stack in a different pull request.

**Comment by dmundra** [comment]
@grugnog I closed and reopened this to redo the checks. Good to add these changes?

**Review by grugnog — APPROVED** [review]

**Pull request merged**
