### PR TITLE
Updating image for sick days for unanet

### PR DESCRIPTION
**Pull request by mgifford**
Worth noting that most of the alt text for images here is rubbish and should be updated with meaningful images when the images are updated.

[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/mgifford-patch-4/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Review by dmundra — CHANGES_REQUESTED** [review]
Thanks, @mgifford. Could the image be local? I think there is an images folder where this could live.

**Comment by mgifford** [comment]
That is definitely better, although not as common in this doc.

**Comment by dmundra** [comment]
@mgifford the image is not found when you try to see it on this page https://handbook.civicactions.com/en/mgifford-patch-4/050-how-we-work/tools/harvest/ (I think a relative path is needed like the previous image).

**Review by dmundra — APPROVED** [review]
Cool. Lets give this a go!

**Pull request merged**
