### PR TITLE
Adding information about Zoom accessibility

### PR DESCRIPTION
**Pull request by mgifford**
[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/mgifford-patch-8/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford looks like `remark-lint` has some feedback for you but it is buried in the details.
* https://github.com/CivicActions/handbook/pull/749/checks?check_run_id=3749155995
* https://github.com/CivicActions/handbook/pull/749/checks?check_run_id=3749164406

**Review by dmundra — CHANGES_REQUESTED** [review]
There is a double 'to to' in the last paragraph.

**Comment by mgifford** [comment]
Should be fixed now.

**Review by dmundra — APPROVED** [review]
Thanks!

**Pull request merged**
