### PR TITLE
Added theme override to adjust the text of the last update date.

### PR DESCRIPTION
**Pull request by dmundra**
Following instructions from:
* https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=custom+translations#custom-translations
* https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure

See preview to confirm text change.

----
:books: Documentation preview :books:: https://civicactions-handbook--1015.org.readthedocs.build/en/1015/

### CODE REVIEW

**Comment by ContentBrewmaster** [comment]
@dmundra Is it possible to remove the colon and add a period to the end of the date?

**Comment by dmundra** [comment]
> @dmundra Is it possible to remove the colon and add a period to the end of the date?

@ContentBrewmaster not by default but I can add another override for that.

**Comment by dmundra** [comment]
@ContentBrewmaster I was able to change the text "to remove the colon and add a period to the end of the date".

**Review by ContentBrewmaster — APPROVED** [review]
Thank you: looks great!

**Pull request merged**
