### PR TITLE
Adding accessibility extensions

### PR DESCRIPTION
**Pull request by mgifford**
[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/mgifford-patch-8/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Review by openprivacy — APPROVED** [review]
Thanks for adding these - are there firefox ones, too?

**Comment by mgifford** [comment]
There are definitely good FF one's @openprivacy. Some are included. I didn't break down the browsers with that list as this is how I had them before. That said, it might be worth while doing.  Might actually make sense to put this in two columns though as often you've got the same software for different browsers...  Might also need to include Edge actually...

**Comment by mgifford** [comment]
Just updated the checks.  Think it should be good now.

**Review by openprivacy — COMMENTED** [review]
I believe that we want to keep the last pass and zoom extensions.

**Pull request merged**
