### PR TITLE
Update project-folder.md

### PR DESCRIPTION
**Pull request by hhartingrex**
Small edits for you, Farooq!

### CODE REVIEW

**Review by farooqzakhilwal — COMMENTED** [review]
Looks good.

**Comment by dmundra** [comment]
> Looks good.

@farooqzakhilwal can you approve the pull request via the 'Files changed' tab? You should see a button to add your review and then options to select this pull request is approved.

**Review by farooqzakhilwal — COMMENTED** [review]
looks good

**Review by farooqzakhilwal — APPROVED** [review]

**Comment by farooqzakhilwal** [comment]
> > Looks good.
> 
> @farooqzakhilwal can you approve the pull request via the 'Files changed' tab? You should see a button to add your review and then options to select this pull request is approved.

@dmundra got it, thanks.

**Comment by dmundra** [comment]
Thanks @farooqzakhilwal. Now either you or @hhartingrex can click the green 'Squash and merge' button. I generally let the author do that.

**Comment by hhartingrex** [comment]
Thanks @dmundra and @farooqzakhilwal :)

**Pull request merged**
