### PR TITLE
Update back-end-development.md

### PR DESCRIPTION
**Pull request by omahane**
We seem to be missing the "NOT" in the outer argument on line 179

### CODE REVIEW

**Review by dmundra — APPROVED** [review]
Good catch. Thank you!

**Comment by omahane** [comment]
@dmundra Thanks for the approval, but I don't think I can merge:
Screen Shot 2022-08-03 at 8 03 35 AM

**Comment by dmundra** [comment]
> @dmundra Thanks for the approval, but I don't think I can merge.

Ah, I noticed you have two accounts. This one https://github.com/christianmburk is in the CA org. I can merge though and let us know if we should add https://github.com/omahane to the CA org.

**Comment by omahane** [comment]
@dmundra How should I ask to have https://github.com/omahane added to the CA org?

**Comment by dmundra** [comment]
> @dmundra How should I ask to have https://github.com/omahane added to the CA org?

You can open an 'Assist' ticket in slack and I think @grugnog or someone will get back to you.

**Pull request merged**
