### PR TITLE
Update expenses.md

### PR DESCRIPTION
**Pull request by ContentBrewmaster**
Updated 1st paragraph to replace "timely" with "within 30 days" and added 2nd paragraph for Canadian instructions.

----
:books: Documentation preview :books:: https://civicactions-handbook--1041.org.readthedocs.build/en/1041/

### CODE REVIEW

**Comment by marctjones** [comment]
I the wording on this needs to be revised a little bit. I am talking to our finance team about the best way to describe expectations and the timeline.

**Review by marctjones — CHANGES_REQUESTED** [review]
Denise can you can the Expense section to read:

Employees are requested to submit expense reports within five (5) business days after returning from a business trip or after incurring the expense(s). Expense reports submitted more than 30 days late may not be processed and paid without approval from the CFO. Outstanding expense reports are justification for CivicActions to withhold travel advances for subsequent trips.

All expense reports must be accurately completed with original receipts that matches each item on the expense report. There is no dollar threshold for required receipts. For those items that do not have a receipt, an explanation must be provided and the employee must attach an approval email (PDF) to indicate that he or she approves the expense to be reimbursed without the receipt. Management reserves the right to disallow reimbursement for expenses without receipts. Expense Reports must be properly approved in order to be processed for reimbursement.

Expense reports must be submitted via from your Unanet Homepage under Expense - [Create Expense Report](https://civicactions.unanet.biz/civicactions/action/expense/add).

**Comment by ContentBrewmaster** [comment]
@marctjones to be clear, you want me to replace ALL the text on expenses.md with the text you provided 2 weeks ago?

**Review by marctjones — APPROVED** [review]
I misunderstood a question from Denise. My fault, her question was clear, I just misinterpreted it. I am going to approve this PR. And I will submit a new PR to restore some content.

**Pull request merged**
