### PR TITLE
Adding an image of the Sales Proposal Process to the Sales Guild page

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by nerdstein** [comment]
We should consider adding this as a new page altogether, something like "Proposal process"

**Comment by kevwalsh** [comment]
Makes sense!  Including the Proposal Roles, @nerdstein ?

**Comment by nerdstein** [comment]
Initial Roles are captured here: https://github.com/CivicActions/handbook/blob/master/docs/07-sales-and-marketing/sales-guild.md#roles-and-accountabilities

**Comment by nerdstein** [comment]
This looks good to me

**Review by erogray — APPROVED** [review]
Changes seem solid from here.

**Pull request merged**
