### PR TITLE
There is a lot more to fix on this page but starting with #celebratin…

### PR DESCRIPTION
**Pull request by mgifford**
…g-diversity

Changing out #dei-ops for #celebrating-diversity

[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/mgifford-patch-7/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Comment by mgifford** [comment]
@grugnog is this approved?

**Comment by grugnog** [comment]
@mgifford it has conflicts

**Comment by mgifford** [comment]
Let me know if that's good now @grugnog

**Review by dmundra — APPROVED** [review]
Thanks @mgifford

**Pull request merged**
