### PR TITLE
Update templates.md

### PR DESCRIPTION
**Pull request by hhartingrex**
Added two new templates and updated others.

----
:books: Documentation preview :books:: https://civicactions-handbook--1072.org.readthedocs.build/en/1072/

### CODE REVIEW

**Review by hhartingrex — COMMENTED** [review]
Tried to fix links to make them (when appropriate) relative

**Comment by dmundra** [comment]
> Tried to fix links to make them (when appropriate) relative

@hhartingrex yup I think those are good. On another page (company-policies/travel-time-tracking-and-expenses.md) it appears there is a broken link, going to 404.

**Comment by farooqzakhilwal** [comment]
@hhartingrex @dmundra is this MR no longer relevant since new fixes were done in a diff [PR](https://github.com/CivicActions/guidebook/pull/1074)?

**Comment by dmundra** [comment]
Looks like it to me. Probably good to close this one.

**Comment by farooqzakhilwal** [comment]
> Looks like it to me. Probably good to close this one.

Sounds good, thanks. @hhartingrex will leave it to you to close this PR.

**Comment by hhartingrex** [comment]
Closing PR (and wanting to learn what happened here also, for future reference!)

**Pull request closed without merging**
