### PR TITLE
Update slack.md

### PR DESCRIPTION
**Pull request by jfremer**
The up-arrow shortcut was removed a while ago.

[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/jfremer-patch-1/ Documentation Status

[//]: # (rtdbot-end)

### CODE REVIEW

**Comment by mgifford** [comment]
The code looks fine but this still seems to be in their help page https://slack.com/help/articles/201374536-Slack-keyboard-shortcuts

That said, it doesn't seem to work for me....  So maybe their help is out of date.

**Review by grugnog — APPROVED** [review]
Up arrow does work for me, but since it seems to be taken out on some platforms I guess we should remove this.

**Comment by mgifford** [comment]
In Ubuntu & Mac for me the up arrow just moves up to the next message in the list. It doesn't behave like a terminal window, and give you the last thing you entered.

**Comment by grugnog** [comment]
Ahh yes, you need to hit "e" also to edit the message. I would be in favor of updating the message rather than deleting it, as some people don't realize editing messages is available/easy and it's much better than posting follow up correction messages that the reader has to piece together.

**Pull request merged**
